# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'zacharygage1 Docker Hub'
        repository: 'zacharygage1/weatherapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
- stage: Provision
  displayName: 'Terraforming on Azure...'
  dependsOn: Build
  jobs: 
  - job: Provision
    displayName: 'Provisioning Container Instance'
    pool: 
      vmImage: ubuntu-latest
    variables: 
    - group: TerraformEnvVars
    steps:
    - script: | 
        set -e 

        terraform init -input=false
        terraform apply -input=false -auto-approve
      name: 'Run_Terraform'
      displayName: 'Run_Terraform'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)